### ISSUE TITLE
Sobrenome maiúsculo em \textcite 

### ISSUE THREAD

**Issue by arantxax** [eekBR/ufpr-abntex2#14]
No Manual de Normatização da UFPR temos a possibilidade de fazer referências:

-  indiretas (p. 82) com `/textcite`  - ex: Silva (2021)
- diretas (p. 83) com `/cite` - ex: (SILVA, 2021)
- e uma terceira especial para fontes de figuras (p. 195) e outros objetos - SILVA (2021)

Utilizar o comando `/textcite{/uppercase{}}` seria uma possibilidade provisória? Também gostaria de saber se já existe um método designado para esse item.

**Comment by eekBR** [comment]
ajustado com o comando \citefg no arquivo 00-pacotes.tex

**Comment by eekBR** [comment]
comando \textcite não gera nome de autor sem os parênteses, por isso foi criado o \citefg

**Comment by arantxax** [comment]
O resultado de `citefig{`} é (AUTOR)((ANO)).

**Comment by ArthurPavezzi** [comment]
Ao utilizar `\textcite{}` dentro do campo de legenda, seja em `\tabela` , em `\qquadro` ou em `\figura` o resultado para mim foi AUTOR (ANO), conforme o Manual de Normalização da UFPR pede.

**Comment by eekBR** [comment]
\citefig corrigido!
