### ISSUE TITLE
Chamada bibliográfica de mesma obra/autores "____."

### ISSUE THREAD

**Issue by arantxax** [eekBR/ufpr-abntex2#15]
As chamadas de texto da bibliografia poderiam ser sucintas quando uma mesma obra é especificada duas ou mais vezes, com mudanças apenas do capítulo, do volume ou da edição utilizando "______."

Exemplos:

- quando há autoria repetida, o sobrenome do autor de vários documentos referenciados sucessivamente pode ser subs-
tituído, nas referências seguintes à primeira, por um traço equivalente a seis caracteres e seguido de ponto final;

- quando o título de várias edições de um documento referenciado sucessivamente for repetido, pode ser substituído por
um traço nas referências seguintes à primeira (o traço deve ser equivalente a seis caracteres e seguido de ponto final);

Procurei nos fóruns de discussão da abntex, mas não tive sorte na busca por termos.

**Comment by eekBR** [comment]
essa é uma opção já implementada, é uma opção do biblatex:
repeatfields= false  - para evitar repetições
repeatfields= true  - para manter repetições
