### ISSUE TITLE
Referência a capítulos de livros e a artigos publicados em anais de eventos sem destaque em negrito

### ISSUE THREAD

**Issue by arantxax** [eekBR/ufpr-abntex2#16]
Na bibliografia, quando é feito referência com artigos publicados em anais de eventos ou apenas uma parte (capítulo) de uma obra, o título da referência não aparece em negrito.
Exemplos:
`@inproceedings{Duarte,
	author = {Márcio Duarte and Alexandre Cardoso and Edgard L. Júnior},
	title = {Realidade Aumentada no Auxílio do Ensino de Física},
	booktitle = {II Workshop de Aplicação de Realidade Virtual},
	date = {2005},
}`

`@incollection{RODARI-MERZAGORA,
author = {Paola Rodari and Matteo Merzagora},
title={Mediadores em museus e centros de ciência:},
subtitle = {Status, papéis e capacitação. Uma visão geral européia},
booktitle = {Diálogos \& ciência: mediação em museus e centros de ciência},
address={Rio de Janeiro},
publisher = {Museu da Vida/Casa de Oswaldo Cruz/Fiocruz},
year={2007},
pages= {7-21},
note = {Organizado por Luisa Massarani, Paola Rodari e Matteo Merzagora},
}`

Output:

CARMEN SÁNCHEZ MORA, María del. Diversos enfoques sobre as visitas guiadasnos museus de ciência. In: DIÁLOGOS & ciência: mediação em museus e centros deciência. Rio de Janeiro: Museu da Vida/Casa de Oswaldo Cruz/Fiocruz, 2007.Organizado por Luisa Massarani, Paola Rodari e Matteo Merzagora. P. 22–27.
DUARTE, Márcio; CARDOSO, Alexandre; JÚNIOR, Edgard L. Realidade Aumentadano Auxílio do Ensino de Física. In: II Workshop de Aplicação de Realidade Virtual.[S.l.: s.n.], 2005.

**Comment by eekBR** [comment]
Os campos indicados não são reconhecidos pelo biblatex-abnt, que é o estilo bibliográfico utilizado para o UFPR.sty.

Veja nas secçõe 6.7-12, (páginas 12-17) da documentação do biblatex-abnt de como utilizar as citações de coleções, em super coleções, parte de livros.

fonte:https://github.com/abntex/biblatex-abnt/blob/master/doc/biblatex-abnt.pdf
