### ISSUE TITLE
Referências sem justificação

### ISSUE THREAD

**Issue by arantxax** [eekBR/ufpr-abntex2#17]
As páginas contendo as referências estão em `\ragged`, quando deveriam ser justificadas.

**Comment by eekBR** [comment]
No Manual de normalização versão reimpressa em 2017, no item d), capítulo 9, pagina 117, as referências são alinhadas pela margem esquerda.

Nos exemplos apresentado na página 118 pode-se perceber que as referências não estão justificadas, e também não são hifenizadas.

Fonte:https://www.portal.ufpr.br/normalizacao.html
