### ISSUE TITLE
Página inicial de capítulos com numeração pequena

### ISSUE THREAD

**Issue by arantxax** [eekBR/ufpr-abntex2#18]
Toda página que inicia um capítulo contém uma numeração aparentemente de tamanho 10, quando o correto é 12.

**Comment by eekBR** [comment]
No Manual de normalização versão reimpressa em 2017, no item c), seção15.3,  pagina 233,  a paginação é com fonte tamanho 10.

Fonte:https://www.portal.ufpr.br/normalizacao.html

**Comment by arantxax** [comment]
Ah, certo. Então é necessário ajustar o restante das páginas que estão em tamanho 12.

Arantxa Eckhardt da Silva

________________________________

**Comment by eekBR** [comment]
Páginas textuais com exceção da página de abertura de capítulo agora com tamanho de fonte ajustado.
