### ISSUE TITLE
Paginação pré-textual

### ISSUE THREAD

**Issue by arantxax** [eekBR/ufpr-abntex2#19]
Todo item pré-textual deve ser contado, mas não numerado. Mas no meu arquivo tenho o seguinte resultado:
- Agradecimentos (não numerado);
- Epígrafe (não numerado);
- Resumo (não numerado);
- Abstract (não numerado);
- Lista de ilustrações (numerado);
- Lista de quadros (numerado);
- Lista de tabelas (numerado);
- Lista de abreviaturas e siglas (não numerado);
- Lista de símbolos (não numerado);
- Sumário (numerado);

Eu tentei aplicar `\pagestyle{empty} \input{00-pretextual}` em `main.tex` e `\thispagestyle{empty}` em cada item após `\ifthenelse{\equal{\terListaQuadros}{Sim}}{` em `00-pretextual.tex`. Infelizmente não obtive solução.

**Comment by eekBR** [comment]
Com o ajuste da numeração na página de abertura de capítulo gerou este problema. Corrigido.
