### ISSUE TITLE
Linhas em branco geradas em \figura

### ISSUE THREAD

**Issue by ArthurPavezzi** [eekBR/ufpr-abntex2#21]
No Manual de Normalização da UFPR o espaçamento textual está definido em 1,5 (p. 233).

Porém, ao criar uma figura entre dois parágrafos (ou no meio de um parágrafo) onde não há espaço naquela página para a figura, há quebra de linha.  A figura muda de página mas o seu espaçamento não.

**Comment by eekBR** [comment]
Olá Arthur,

Primeiramente, obrigado por utilizar a customização da ABNTeX para a UFPR, e pelo comentário a respeito do espaçamento de figuras no documento.

Se você está utilizando o comando \figura, ou \figurac ou \imagem para inserir uma imagem, esses comandos já consideram o espaçamento antes e depois da imagem(float).

Se o espaçamento é maior, a distribuição dos elementos textuais ao longo da página é balanceada para que a imagem fique o mais próximo possível do ponto de inserção. Há inúmeros casos em que isso ocorre, dentre eles:

  1.  no caso de haver um título de capítulo, seção, subsecção próximo ao float, o LaTeX não deixará o título órfão, isto é isolado no final da página e o posicionará na página seguinte. Fazendo com que a distribuição do texto e dos floats na página sejam mais espaçadas;
  2.  no caso de haver algum ambiente (itemize, enumerate, description, equation, quotation, minipage,...) que exige a apresentação em uma nova página ou uma distribuição de espaçamentos, ou uma quebra entre os itens apresentados. O que fará que os elementos sejam redistribuídos;
  3.  no caso de haver texto após o float, desde que não recaia nos dois casos mencionados anteriormente, o LaTeX posiciona a figura na página seguinte; preenche o espaço deixado com o texto mencionado. Caso ocorra alguma das situações acima, o LaTeX aumentará o espaçamento entre os elementos da página.
  4.  ou até mesmo a alteração de opções na distribuição dos floats (htpb).

Apenas lembro que ABNT não prevê a inserção de figuras no meio de um parágrafo, apesar do LaTeX poder fazê-lo com inúmeras possibilidades, dentre elas o \includegraphics. Este comando não gera quebra de linha a não ser que você o estabeleça, e também este comando não insere ou altera os espaçamentos.

Emílio Eiji Kavamura
Depto de Expressão Gráfica
Centro Politécnico - UFPR
________________________________
De: Arthur Pavezzi ***@***.***>
Enviado: terça-feira, 6 de julho de 2021 09:09
Para: eekBR/ufpr-abntex2 ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [eekBR/ufpr-abntex2] Linhas em branco geradas em \figura (#21)


No Manual de Normalização da UFPR o espaçamento textual está definido em 1,5 (p. 233).

Porém, ao criar uma figura entre dois parágrafos (ou no meio de um parágrafo) onde não há espaço naquela página para a figura, há quebra de linha. A figura muda de página mas o seu espaçamento não.

**Comment by ArthurPavezzi** [comment]
Eu que agradeço pela disponiblização e manutenção desta customização do ABNTeX para a UFPR.

Acredito que meu comentário não tenha sido muito claro: há quebras de linha extra quando há a geração de uma imagem/figura/gráfico. Anexo aqui uma captura da minha tela para mostrar o meu código .tex e o que está acontecendo no pdf compilado. 

![image](https://user-images.githubusercontent.com/18685164/124769916-43820f80-df10-11eb-8779-3bca3ad2177c.png)

**Comment by eekBR** [comment]
Olá Arthur,

Desculpe a demora...

Agora entendi o que você quis dizer, perdão. Com a cabeça mergulhada na tese e nas aulas remotas não está muito fácil me concentrar.

Estive tentando recriar e entender como resolver o problema... mas meus arreios esticaram, vou precisar de mais um tempinho para descobrir algo
coerente e eficiente.

Agradeço pela sua atenção e paciência.

At.te,

Emílio Eiji Kavamura
Depto de Expressão Gráfica
Centro Politécnico - UFPR
________________________________
De: Arthur Pavezzi ***@***.***>
Enviado: quarta-feira, 7 de julho de 2021 10:48
Para: eekBR/ufpr-abntex2 ***@***.***>
Cc: Emilio Eiji Kavamura ***@***.***>; Comment ***@***.***>
Assunto: Re: [eekBR/ufpr-abntex2] Linhas em branco geradas em \figura (#21)


Eu que agradeço pela disponiblização e manutenção desta customização do ABNTeX para a UFPR.

Acredito que meu comentário não tenha sido muito claro: há quebras de linha extra quando há a geração de uma imagem/figura/gráfico. Anexo aqui uma captura da minha tela para mostrar o meu código .tex e o que está acontecendo no pdf compilado.

[image]<https://user-images.githubusercontent.com/18685164/124769916-43820f80-df10-11eb-8779-3bca3ad2177c.png>

**Comment by eekBR** [comment]
o espaçamento no comando figura foi corrigido está no commit d4fee96, outros comandos: o figurac e imagem também foram corrigidos. Muito obrigado @ArthurPavezzi por me alertar!!!
