### ISSUE TITLE
\autoref{} de \qquadro apresenta erros

### ISSUE THREAD

**Issue by ArthurPavezzi** [eekBR/ufpr-abntex2#22]
Ao utilizar `\autoref{qua:label}` para referenciar um quadro feito com o comando `\qquadro` e a etiqueta `label`, O resultado é apenas o número do capítulo ou seção.

Exemplo funcional mínimo (adicionar este texto na linha 3 do arquivo cap01.tex):
```latex
Texto texto texto \autoref{qua:teste}

\qquadro{Teste de quadros}%TITULO
{% Aqui inicia os elementos tabulados
\begin{tabular}
{|cc|}
\hline
A & B\\\hline
1 & 2\\\hline
\end{tabular}
}% Aqui termina os elementos tabulados
{Sem fonte}% Fonte
{teste} % Etiqueta da tabela tab:Etiqueta
{Nota} % notas
{Legenda}% legenda

**Comment by eekBR** [comment]
comentário: temos três ambientes: o minipage que incopora o quadro que por sua vez incorpora o tabular. O minipage tem a largura ajustada para a do ambiente tabular. No seu exemplo a largura do tabular ficou muito pequena para se colocar os textos.
Sim, eu estou travado por não conseguir comparar a largura do tabular com um valor numérico + unidade de medida.
