### ISSUE TITLE
Negrito em referências.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eekBR/ufpr-abntex2#6]
```
Pela norma o título da referẽncia deve estar em negrito e não está na 
parte de referẽncias



```

Original issue reported on code.google.com by `thiago...@gmail.com` on 13 Jun 2015 at 5:18

**Comment by eekBR** [comment]
Implementado. Obrigado por sua colaboração.

**Comment by eekBR** [comment]
Ajuste da opção dos títulos em destaque utilizando negrito ou itálico no arquitvo 00-pacotes.tex nas linhas 27 a 29.
