### ISSUE TITLE
Capa e captions

### ISSUE THREAD

**Issue by carmo-lucas** [eekBR/ufpr-abntex2#9]
Pela Norma mais recente da UFPR apenas o título deve estar em negrito na capa e na contracapa.

As **captions** também devem estar todas em **uppercase** tanto no texto quanto no sumário.

Eu testei alguma configurações no UFPR.sty mas não consegui fazer essas alterações por que não tenho muita experiência em LaTeX.

Também tive alguns problemas para adicionar as referências (copiei o texto que estava usando em um documento com o pacote AbnTeX2 sem modificações).

**Comment by eekBR** [comment]
Olá, eu atualizei a capa (não notei que o formato da capa havia mudado) e os uppercase nos títulos foram corrigidos.
